- name: Update system
  apt:
    update_cache: yes
    upgrade: dist

- name: Install general tools
  apt:
    name:
      - git
      - curl
      - htop
      - vim
      - net-tools
      - unzip
      - dkms
      - linux-headers-generic
      - iw
      - samba
      - python3-pip
      - python3-venv
    state: present
    
- name: Create virtualenv for ros2_gateway
  command: python3 -m venv /home/drone/ros2_gateway_venv
  args:
    creates: /home/drone/ros2_gateway_venv

- name: Install uvicorn in virtualenv
  pip:
    name: uvicorn[standard]
    virtualenv: /home/drone/ros2_gateway_venv
    
- name: Reboot the system
  ansible.builtin.reboot:
    reboot_timeout: 600
    test_command: whoami
  become: yes

- import_tasks: ssh.yml
  when: ssh_private_key is defined and ssh_public_key is defined

- name: Register Samba Share
  block:
    - name: Create Samba share directory
      file:
        path: /home/drone/RecorderShare
        state: directory
        owner: drone
        group: drone
        mode: '0777'

    - name: Add Ansible MANAGED BLOCK marker
      lineinfile:
        path: /etc/samba/smb.conf
        line: "# {mark} ANSIBLE MANAGED BLOCK RecorderShare"
        state: present
        insertafter: EOF


    - name: Ensure Samba share configuration is present
      blockinfile:
        path: /etc/samba/smb.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK RecorderShare"
        block: |
          [RecorderShare]
          path = /home/drone/RecorderShare
          browseable = yes
          read only = no

    - name: Restart Samba service
      service:
        name: smbd
        state: restarted

    - name: Update the firewall rules to allow Samba traffic
      ufw:
        rule: allow
        name: Samba

- name: Add Samba user with predefined password
  shell: echo -e "{{ samba_password }}\n{{ samba_password }}" | smbpasswd -a drone -s
  args:
    executable: /bin/bash
  when: samba_password is defined