- name: Update system
  apt:
    update_cache: yes
    upgrade: dist

- name: Install general tools
  apt:
    name:
      - git
      - curl
      - htop
      - vim
      - net-tools
      - unzip
      - dkms
      - iw
    state: present

- name: Gather loaded kernel modules
  setup:
    filter: ansible_modules

- name: Install RTL8192EU driver for TP-Link TL-WN823N v3
  block:
    - name: Check if RTL8192EU driver is already installed
      stat:
        path: /lib/modules/{{ ansible_kernel }}/updates/dkms/8192eu.ko
      register: rtl8192eu_driver

    - name: Clone updated RTL8192EU driver from clnhub
      git:
        repo: https://github.com/clnhub/rtl8192eu-linux.git
        dest: /usr/src/rtl8192eu-1.0
        version: master
      when: not rtl8192eu_driver.stat.exists

    - name: Disable I386 platform in Makefile
      lineinfile:
        path: /usr/src/rtl8192eu-1.0/Makefile
        regexp: '^CONFIG_PLATFORM_I386_PC = y'
        line: 'CONFIG_PLATFORM_I386_PC = n'
      when: not rtl8192eu_driver.stat.exists

    - name: Enable ARM64 Raspberry Pi platform in Makefile
      lineinfile:
        path: /usr/src/rtl8192eu-1.0/Makefile
        regexp: '^CONFIG_PLATFORM_ARM_AARCH64 = n'
        line: 'CONFIG_PLATFORM_ARM_AARCH64 = y'
      when: not rtl8192eu_driver.stat.exists

    - name: Create dkms.conf for rtl8192eu
      copy:
        dest: /usr/src/rtl8192eu-1.0/dkms.conf
        content: |
          PACKAGE_NAME="rtl8192eu"
          PACKAGE_VERSION="1.0"
          BUILT_MODULE_NAME[0]="8192eu"
          DEST_MODULE_LOCATION[0]="/kernel/drivers/net/wireless"
          AUTOINSTALL="yes"
          MAKE[0]="make all"
          CLEAN="make clean"
      when: not rtl8192eu_driver.stat.exists

    - name: Build and install the driver with DKMS
      shell: |
        dkms remove rtl8192eu/1.0 --force || true
        dkms add -m rtl8192eu -v 1.0
        dkms build rtl8192eu/1.0
        dkms install rtl8192eu/1.0
      args:
        creates: /lib/modules/{{ ansible_kernel }}/updates/dkms/8192eu.ko
      when: not rtl8192eu_driver.stat.exists

    - name: Load the RTL8192EU module manually if not loaded
      shell: |
        insmod /lib/modules/{{ ansible_kernel }}/updates/dkms/8192eu.ko
      args:
        executable: /bin/bash
      when:
        - not rtl8192eu_driver.stat.exists
        - "'8192eu' not in ansible_facts.modules"