- name: Get Ethernet usb adapter name
  shell: |
    ls /sys/class/net | grep -E 'enx[0-9a-f]{12}'
  register: ethernet_usb_adapter_name
  changed_when: false
  failed_when: false

- name: Get the usb vendor and product id
  shell: |
    lsusb | grep -E 'Realtek' | awk '{print $6}'
  register: usb_vendor_product_id
  changed_when: false
  when: ethernet_usb_adapter_name.stdout == ""

- name: Reset the usb adapter via usb_modeswitch
  become: true
  shell: |
    usb_modeswitch -v {{ usb_vendor_product_id.stdout.split(':')[0] }} -p {{ usb_vendor_product_id.stdout.split(':')[1] }} --reset-usb
  when: ethernet_usb_adapter_name.stdout == "" and usb_vendor_product_id.stdout != ""
  register: usb_modeswitch_result

- name: Wait until TP-Link Ethernet usb adapter is listed
  shell: ls /sys/class/net | grep -E 'enx[0-9a-f]{12}'
  register: ethernet_usb_adapter_name
  retries: 10
  delay: 3
  until: ethernet_usb_adapter_name.rc == 0
  when: usb_modeswitch_result is changed

- name: Set a fixed IP address for the ethernet usb adapter in the /etc/netplan/01-network-manager-all.yaml file
  become: true
  blockinfile:
    path: /etc/netplan/01-network-manager-all.yaml
    create: yes
    state: present
    mode: '0600'
    block: |
      network:
        version: 2
        ethernets:
          {{ ethernet_usb_adapter_name.stdout }}:
            addresses: [192.168.1.5/24]
            dhcp4: no
            

- name: Apply the netplan configuration
  become: true
  command: netplan apply