- name: Add ROS 2 GPG key
  apt_key:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc
    state: present

- name: Add ROS 2 apt repository
  apt_repository:
    repo: "deb [arch=arm64] http://packages.ros.org/ros2/ubuntu jammy main"
    state: present
    filename: ros2-latest

- name: Install ROS 2 base packages
  apt:
    name:
      - ros-humble-ros-base
      - python3-colcon-common-extensions
      - python3-argcomplete
      - ros-dev-tools
    state: present
    update_cache: yes

- name: Source ROS 2 in .bashrc
  lineinfile:
    path: /home/drone/.bashrc
    line: "source /opt/ros/humble/setup.bash"
    state: present
    insertafter: EOF
  become: yes
  become_user: drone

- name: Create directory for ROS 2 workspace
  file:
    path: /home/drone/ros2_drone_ws
    state: directory
    owner: drone
    group: drone
    mode: '0755'

- name: Initialize rosdep
  command: rosdep init
  args:
    creates: /etc/ros/rosdep/sources.list.d/20-default.list
  become_user: drone
  become: yes

- name: Update rosdep
  command: rosdep update
  args:
    warn: false
  become_user: drone
  become: yes