- name: Download latest ROS 2 GPG key
  ansible.builtin.shell: |
    curl -fsSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | gpg --dearmor | tee /usr/share/keyrings/ros-archive-keyring.gpg > /dev/null
  args:
    creates: /usr/share/keyrings/ros-archive-keyring.gpg
  become: yes

- name: Add ROS 2 apt repository with signed-by keyring
  ansible.builtin.apt_repository:
    repo: "deb [arch=arm64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu noble main"
    filename: ros2
    state: present
  become: yes

- name: Install ROS 2 base packages
  apt:
    name:
      - ros-jazzy-ros-base
      - python3-colcon-common-extensions
      - python3-argcomplete
      - ros-dev-tools
    state: present
    update_cache: yes

- name: Source ROS 2 in .bashrc
  lineinfile:
    path: /home/drone/.bashrc
    line: "source /opt/ros/jazzy/setup.bash"
    state: present
    insertafter: EOF
  become: yes
  become_user: drone

- name: Create directory for ROS 2 workspace
  file:
    path: /home/drone/ros2_drone_ws
    state: directory
    owner: drone
    group: drone
    mode: '0755'

- name: Initialize rosdep
  command: rosdep init
  args:
    creates: /etc/ros/rosdep/sources.list.d/20-default.list

- name: Update rosdep
  command: rosdep update
  become_user: drone
  become: false
