- name: Download the ROS 2 driver for Libcamera
  git:
    repo: "git@github.com:AlZi-88/libcamera_node.git"
    dest: /home/drone/ros2_drone_ws/src/libcamera_node
    version: main
    update: yes
  become_user: drone

- name: Build the ROS 2 driver for Libcamera
  shell: |
    source /opt/ros/jazzy/setup.bash
    source /home/drone/ros2_drone_ws/install/setup.bash
    colcon build --packages-select libcamera_node
  args:
    executable: /bin/bash
    chdir: /home/drone/ros2_drone_ws
  become_user: drone

- name: Install the ROS 2 driver for Libcamera systemd service
  become: true
  copy:
    src: /home/drone/ros2_drone_ws/src/libcamera_node/service/libcamera_node.service
    dest: /etc/systemd/system/libcamera_node.service
    remote_src: true
    mode: '0644'

- name: Reload systemd and enable driver service
  become: true
  systemd:
    name: libcamera_node.service
    daemon_reload: yes
    enabled: yes
    state: started