- name: Download the ROS 2 driver for Libcamera
  git:
    repo: "git@github.com:AlZi-88/libcamera_node.git"
    dest: /home/drone/ros2_drone_ws/src/libcamera_node
    version: main
    update: yes
  become_user: drone

- name: Install dependencies for the ROS2 driver for libcamera_node
  shell: |
    source /opt/ros/jazzy/setup.bash
    rosdep install --from-paths src --ignore-src -y -r
  args:
    executable: /bin/bash
  become_user: drone

- name: Build the ROS 2 driver for Libcamera
  shell: |
    source /opt/ros/jazzy/setup.bash
    colcon build --packages-select libcamera_node
  args:
    executable: /bin/bash
    chdir: /home/drone/ros2_drone_ws
  become_user: drone