- name: Install Node js
  import_tasks: NodeJS.yml

- name: Upgrade bundled npm to latest version
  npm:
    name: npm
    global: yes
    state: latest
  become: yes

- name: Deploy SkyCommander
  import_tasks: deploy_skycommanderapp.yml

- name: Deploy SkyCommander Agent
  import_tasks: deploy_skycommanderagent.yml