- name: Install Node.js 20.x via Nodesource
  become: true
  block:
    - name: Remove old nodejs version if present
      apt:
        name: 
          - nodejs
          - nodejs-doc
          - libnode-dev
        state: absent
        purge: yes

    - name: Download and install NodeSource GPG key
      shell: |
        curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor | tee /usr/share/keyrings/nodesource.gpg > /dev/null
      args:
        creates: /usr/share/keyrings/nodesource.gpg
      become: yes

    - name: Add Node.js 20.x repo to sources list
      apt_repository:
        repo: "deb [arch=arm64 signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main"  # Replace 'nodistro' with your actual distribution codename once available
        state: present
        filename: nodesource

    - name: Install Node.js
      apt:
        name: nodejs
        state: present
        update_cache: true

    - name: Ensure npm is up-to-date
      shell: npm install -g npm
      args:
        creates: /usr/local/bin/npm

    - name: Check Node version
      command: node -v
      register: node_version

    - name: Debug Node version
      debug:
        var: node_version.stdout