
- name: Setup base system and ROS 2
  hosts: all
  become: yes

  vars_prompt:
    - name: "target_ip"
      prompt: "Enter the IP address of the Target Raspberry Pi"

  roles:
    - base
    - ros2

- name: Add PX4 repositories to ROS 2 workspace
  hosts: all
  become: yes

  roles:
    - px4

- name: Build ROS 2 workspace with PX4 packages
  hosts: all
  become: yes

  tasks:
    - import_role:
        name: ros2
        tasks_from: build

