- name: Setup base system
  hosts: all
  become: yes
  tasks:
    - import_role:
        name: base
        tasks_from: setup_base

- name: Setup SSH
  hosts: all
  become: yes
  tasks:
    - import_role:
        name: base
        tasks_from: ssh

- name: Install ROS2
  hosts: all
  become: yes
  tasks:
    - import_role:
        name: ros2
        tasks_from: setup_ros2

- name: Setup samba share on compi
  hosts: compi
  become: yes
  tasks:
    - import_role:
        name: base
        tasks_from: samba

- name: Add PX4 Repositories to ROS 2 Workspace
  hosts: compi
  become: yes
  roles:
    - px4

- name: Build ROS 2 PX4 packages
  hosts: compi
  become: no
  tasks:
    - import_role:
        name: ros2
        tasks_from: build_px4_nodes

- name: Configure Lidar Ethernet Interface
  hosts: compi
  tasks:
    - import_role:
        name: lidar
        tasks_from: ethernet_config

- name: Install Lidar SDK
  hosts: compi
  tasks:
    - import_role:
        name: lidar
        tasks_from: livox_sdk_installation

- name: Install Lidar Driver
  hosts: compi
  tasks:
    - import_role:
        name: lidar
        tasks_from: ros2_driver_installation

- name: Install Camera libraries
  hosts: [compi campi]
  tasks:
    - import_role:
        name: camera
        tasks_from: 
          - general
          - install_camera_libraries
          - libcamera_ros2_driver

- name: Build SkyCommanderBackend
  hosts: compi
  become: no
  tasks:
    - import_role:
        name: ros2
        tasks_from: build_skycommanderbackend

- name: Install and Configure Docker
  hosts: compi
  become: yes
  tasks:
    - import_role:
        name: docker
        tasks_from: docker

- name: Install SkyCommanderApp
  hosts: compi
  roles:
    - SkyCommanderApp

- name: Reboot the system
  hosts: all
  become: yes
  tasks:
  - ansible.builtin.reboot:
      reboot_timeout: 600
      test_command: whoami # Verify that the system is accessible after reboot by checking the current user

