
- name: Setup base system and ROS 2
  hosts: all
  become: yes

  vars_prompt:
    - name: "target_ip"
      prompt: "Enter the IP address of the Target Raspberry Pi"

  roles:
    - base
    - ros2

- name: Add PX4 Repositories to ROS 2 Workspace
  hosts: all
  become: yes
  roles:
    - px4

- name: Build ROS 2 workspace with PX4 packages
  hosts: all
  become: yes
  tasks:
    - import_role:
        name: ros2
        tasks_from: build

- name: Install and Configure Docker
  hosts: all
  become: yes
  tasks:
    - import_role:
        name: docker
        tasks_from: docker

- name: Install SkyCommanderApp
  hosts: all
  roles:
    - SkyCommanderApp

- name: Reboot the system
  hosts: all
  become: yes
  tasks:
  - ansible.builtin.reboot:
      reboot_timeout: 600
      test_command: whoami # Verify that the system is accessible after reboot by checking the current user

