- name: Setup DroneComPi Ubuntu
  hosts: all
  become: yes

  roles:
    - base
    - docker
    - ros2

  tasks:
    - name: Update system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install general tools
      apt:
        name:
          - git
          - curl
          - htop
          - vim
          - net-tools
          - unzip
        state: present

    - name: Install GUI (optional)
      apt:
        name:
          - ubuntu-desktop
        state: present
      when: gui | default(false)  # true = with desktop, false = headless
