name: Generate Architecture Diagrams

on:
  push:
    branches:
      - main
      - docu/*
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  
  export-diagrams:
    name: Export Structurizr Diagrams and Update README
    runs-on: [self-hosted, raspi, arm64]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Export diagrams using Structurizr CLI in plantUML
        working-directory: docs/architecture
        run: |
          mkdir -p diagrams
          /opt/structurizr/structurizr.sh export -workspace workspace.dsl -format plantuml -output diagrams

      - name: Convert PlantUML to PNG
        working-directory: docs/architecture/diagrams
        run: |
          java -jar /opt/structurizr/plantuml.jar -t png *.puml
          
      - name: Update README with diagrams
        run: |
          diagrams_md=""
          for img in docs/architecture/diagrams/*.png; do
            filename=$(basename "$img")
            label=${filename%.*}
            label=$(echo "$label" | sed -e 's/-/ /g' -e 's/\b\(.\)/\u\1/g')
            diagrams_md+="![${label}](docs/architecture/diagrams/${filename})\n"
          done

          awk -v new_content="$diagrams_md" '
            BEGIN {in_block=0}
            /<!-- diagrams:start -->/ {print; print new_content; in_block=1; next}
            /<!-- diagrams:end -->/ {in_block=0}
            !in_block
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit updated diagrams and README
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md docs/architecture/diagrams
          git commit -m "Update Structurizr diagrams in README"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          #git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
