name: Provision and Test Target Pi

on:
  push:
    branches:
      - main
      - infra/*
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Target Pi via Ansible
    runs-on: [self-hosted, raspi, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run playbook to provision target
        working-directory: ansible
        run: |
          ansible-playbook playbook.yml \
            --inventory inventory/target.yaml \
            --extra-vars "target_ip=${{ secrets.TARGET_PI_IP }} target_password=${{ secrets.DRONE_USER_PASSWORD }}" \
        env:
          ANSIBLE_HOST_KEY_CHECKING: False

  test:
    name: Smoke Test ROS2 Interfaces
    runs-on: 
      - self-hosted
      - raspi
      - arm64
    needs: deploy

    steps:
      - name: Check PX4 Interfaces via SSH
        run: |
          ssh -o StrictHostKeyChecking=no drone@${{ secrets.TARGET_PI_IP }} << 'EOF'
            source /opt/ros/humble/setup.bash
            source /home/drone/ros2_drone_ws/install/setup.bash
            ros2 interface list | grep px4_msgs/msg/VehicleStatus
          EOF