name: Provision and Test Target Pi

on:
  push:
    branches:
      - main
      - infra/*
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/export-documentation.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Target Pi via Ansible
    runs-on: [self-hosted, raspi, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run playbook to provision target
        working-directory: ansible
        run: |
          ansible-playbook playbook.yml \
            --inventory inventory/target.yaml \
            --extra-vars "target_ip=${{ secrets.TARGET_PI_IP }} target_password=${{ secrets.DRONE_USER_PASSWORD }}" \
        env:
          ANSIBLE_HOST_KEY_CHECKING: False

  test:
    name: Smoke Test ROS2 Interfaces
    runs-on: 
      - self-hosted
      - raspi
      - arm64
    needs: deploy

    steps:
      - name: Check PX4 Interfaces via SSH
        run: |
          ssh -o StrictHostKeyChecking=no drone@${{ secrets.TARGET_PI_IP }} << 'EOF'
          source /home/drone/.bashrc
          ros2 interface list | grep px4_msgs/msg/VehicleStatus
          EOF

      - name: Verify TP-Link WiFi Adapter Presence
        run: |
              ssh -o StrictHostKeyChecking=no drone@${{ secrets.TARGET_PI_IP }} << 'EOF'
              interfaces=$(ip -o link show | awk -F': ' '{print $2}')
              has_wlan0=false
              has_wlx=false
              for iface in $interfaces; do
                [[ "$iface" == "wlan0" ]] && has_wlan0=true
                [[ "$iface" == wlx* ]] && has_wlx=true
              done
              if $has_wlan0 && $has_wlx; then
                echo "Found both interfaces"
              else
                echo "Missing interfaces"
                exit 1
              fi
              EOF
        shell: bash

