name: Provision and Test Target Pi

on:
  push:
    branches:
      - main
      - infra/*
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/export-documentation.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Target Pi via Ansible
    runs-on: [self-hosted, raspi, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate TARGET_PI_IP secret
        run: |
          if [ -z "${{ secrets.TARGET_PI_IP }}" ]; then
            echo "Error: TARGET_PI_IP secret is not set."
            exit 1
          fi

      - name: Validate DRONE_USER_PASSWORD secret
        run: |
          if [ -z "${{ secrets.DRONE_USER_PASSWORD }}" ]; then
            echo "Error: DRONE_USER_PASSWORD secret is not set."
            exit 1
          fi

      - name: Validate SSH_PRIVATE_KEY secret
        run: |
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "Error: SSH_PRIVATE_KEY secret is not set."
            exit 1
          fi

      - name: Validate SSH_PUBLIC_KEY secret
        run: |
          if [ -z "${{ secrets.SSH_PUBLIC_KEY }}" ]; then
            echo "Error: SSH_PUBLIC_KEY secret is not set."
            exit 1
          fi

      - name: Run playbook to provision target
        working-directory: ansible
        run: |
          ansible-playbook playbook.yml \
            --inventory inventory/target.yaml \              
            --extra-vars "target_ip=${{ secrets.TARGET_PI_IP }} \
                    target_password=${{ secrets.DRONE_USER_PASSWORD }} \
                    samba_password=${{ secrets.DRONE_USER_PASSWORD }} \
                    ssh_private_key=${{ secrets.SSH_PRIVATE_KEY }} \
                    ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
        env:
          ANSIBLE_HOST_KEY_CHECKING: False

  test:
    name: Smoke Test ROS2 Interfaces
    runs-on: 
      - self-hosted
      - raspi
      - arm64
    needs: deploy

    steps:
      - name: Check PX4 Interfaces via SSH
        run: |
          ssh -o StrictHostKeyChecking=no drone@${{ secrets.TARGET_PI_IP }} << 'EOF'
          source /opt/ros/humble/setup.bash
          source /home/drone/ros2_drone_ws/install/setup.bash
          ros2 interface list | grep px4_msgs/msg/VehicleStatus
          EOF

      - name: Verify TP-Link WiFi Adapter Presence
        run: |
              ssh -o StrictHostKeyChecking=no drone@${{ secrets.TARGET_PI_IP }} << 'EOF'
              interfaces=$(ip -o link show | awk -F': ' '{print $2}')
              has_wlan0=false
              has_wlx=false
              for iface in $interfaces; do
                [[ "$iface" == "wlan0" ]] && has_wlan0=true
                [[ "$iface" == wlx* ]] && has_wlx=true
              done
              if $has_wlan0 && $has_wlx; then
                echo "Found both interfaces"
              else
                echo "Missing interfaces"
                exit 1
              fi
              EOF
        shell: bash

      - name: Verify RecorderShare is mounted and accessible from Runner
        run: |
          echo "${{ secrets.DRONE_USER_PASSWORD }}" | sudo -S mkdir -p /mnt/recordershare
          # Check if the directory is already mounted
          if ! mountpoint -q /mnt/recordershare; then
            echo "${{ secrets.DRONE_USER_PASSWORD }}" | sudo -S mount -t cifs -o username=drone //${{ secrets.TARGET_PI_IP }}/RecorderShare /mnt/recordershare
          else
            echo "/mnt/recordershare is already mounted."
          fi
          testfile="/mnt/recordershare/github_testfile.txt"
          echo "Testing SMB share access" | sudo tee $testfile
          if [ -f "$testfile" ]; then
            echo "File written successfully"
            sudo rm $testfile
          else
            echo "Failed to write file to SMB share"
            exit 1
          fi
        shell: bash

