# .github/workflows/test-runner.yml
name: Test Local Runner

on:
  workflow_dispatch:  # manuell starten

jobs:
  echo-test:
    runs-on: [self-hosted]  # must fit to the labels with which the runner was configured
    steps:
      - name: Say hello
        run: echo "Hello from compirunner :)"
